### ISSUE TITLE
build fails -- wrong subdirectory name?

### ISSUE THREAD

**Issue by greg-minshall** [kunamech/stardict-con#1]
hi.  i get failures because of the `cd` on line 19 of `PKGBUILD`.  the name of the subdirectory appears to be `guncel-turkce-sozluk_turk-dil-kurumu-2011/`, not `Güncel Türkçe...`

**Comment by logkos** [comment]
Sorry for being late and this issue. Should be fixed now.

**Comment by greg-minshall** [comment]
works great -- thanks very much!
